---
title: "DMUBA TP01"
output: html_notebook
---

Carga inicial del dataframe de tweets COVID-19
```{r}
library(mongolite)
library(ggplot2)
library(dplyr)

tweets_mongo_covid19 <- mongo(
  collection = "tweets_mongo_covid19", 
  db = "DMUBA"
)
```

# Análisis de Perfiles
Desplegamos todos los perfiles
```{r}
profiles = tweets_mongo_covid19$find(fields=
'{
      "user_id": 1,
      "screen_name": 1,
      "verified": 1,
      "location": 1,
      "source": 1,
      "favorite_count": 1,
      "retweet_count": 1,
      "statuses_count": 1,
      "followers_count": 1,
      "friends_count": 1,
        
      "retweet_user_id": 1,
      "retweet_screen_name": 1,
      "retweet_verified": 1,
      "retweet_location": 1,
      "retweet_source": 1,
      "retweet_favorite_count": 1,
      "retweet_retweet_count": 1,
      "retweet_statuses_count": 1,
      "retweet_followers_count": 1,
      "retweet_friends_count": 1,
      
      "quoted_user_id": 1,
      "quoted_screen_name": 1,
      "quoted_verified": 1,
      "quoted_location": 1,
      "quoted_source": 1,
      "quoted_favorite_count": 1,
      "quoted_retweet_count": 1,
      "quoted_statuses_count": 1,
      "quoted_followers_count": 1,
      "quoted_friends_count": 1
}'
)
```

Combinamos los perfiles de los tweets originales, retweets y quotes involucrados
```{r}
original_profiles_header <- c(
  'user_id',
  'screen_name',
  'verified',
  'location',
  'source',
  'favorite_count',
  'retweet_count',
  'statuses_count',
  'followers_count',
  'friends_count'
)
original_profiles = profiles[,original_profiles_header]
```

```{r}
retweeted_profiles_header <- c(
  'retweet_user_id',
  'retweet_screen_name',
  'retweet_verified',
  'retweet_location',
  'retweet_source',
  'retweet_favorite_count',
  'retweet_retweet_count',
  'retweet_statuses_count',
  'retweet_followers_count',
  'retweet_friends_count'
)

retweeted_profiles = profiles[,retweeted_profiles_header]

names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_user_id'] <- 'user_id'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_screen_name'] <- 'screen_name'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_verified'] <- 'verified'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_location'] <- 'location'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_source'] <- 'source'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_favorite_count'] <- 'favorite_count'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_retweet_count'] <- 'retweet_count'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_statuses_count'] <- 'statuses_count'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_followers_count'] <- 'followers_count'
names(retweeted_profiles)[names(retweeted_profiles) == 'retweet_friends_count'] <- 'friends_count'
```

```{r}
quoted_profiles_headers <- c(
  'quoted_user_id',
  'quoted_screen_name',
  'quoted_verified',
  'quoted_location',
  'quoted_source',
  'quoted_favorite_count',
  'quoted_retweet_count',
  'quoted_statuses_count',
  'quoted_followers_count',
  'quoted_friends_count'
)
quoted_profiles = profiles[,quoted_profiles_headers]

names(quoted_profiles)[names(quoted_profiles) == 'quoted_user_id'] <- 'user_id'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_screen_name'] <- 'screen_name'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_verified'] <- 'verified'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_location'] <- 'location'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_source'] <- 'source'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_favorite_count'] <- 'favorite_count'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_retweet_count'] <- 'retweet_count'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_statuses_count'] <- 'statuses_count'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_followers_count'] <- 'followers_count'
names(quoted_profiles)[names(quoted_profiles) == 'quoted_friends_count'] <- 'friends_count'
```

Combinamos y aplicamos transformaciones
```{r}
combined_profiles = rbind(original_profiles, retweeted_profiles, quoted_profiles)

tweet_profiles_df = combined_profiles[!duplicated(combined_profiles),]
```
